micronaut:
  application:
    name: abi_accounts
  security:
    enabled: true
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
datasources:
  default:
    db-type: postgres
    dialect: POSTGRES
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${PG_HOST}:${PG_PORT}/${PG_DBNAME}
    username: ${PG_USER}
    password: ${PG_PASSWORD}
    schema: accounts_schema
